service: sls-example

provider:
  name: aws
  region: eu-central-1
  ecr:
    images:
      slsexample:
        path: ./

functions:
  get_image:
    image:
      name: slsexample
      entryPoint:
        - /usr/local/bin/python
        - -m
        - awslambdaric
      command:
        handler.get_image
    events:
      - httpApi:
          path: /image
          method: get