service: sls-example

provider:
  name: aws
  region: eu-central-1
  ecr:
    images:
      appimage:
        path: ./

functions:
  process_image:
    image:
      name: appimage
      entryPoint:
        - /usr/local/bin/python
        - -m
        - awslambdaric
      command:
        handler.process_image
    events:
      - httpApi:
        path: /transform
        method: get